#!/bin/sh /etc/rc.common
#
	# Name:         1xClient
	# Version:      2.0
	# Description:  1xClient Startup Configuration
	# Created:      2019-03-01
	# Copyright (C) 2019-2022 Hsy <info@hsy.ink>
#

START=30
USE_PROCD=1

Controller_1xClient()
{
	local enable
	config_get_bool enable $1 enable

	if [ $enable = 1 ]; then
		local username
		local password
		local ifname
		local debug

		config_get username $1 username
		config_get password $1 password
		config_get ifname $1 ifname
		config_get debug $1 debug

		procd_open_instance
		procd_set_param command /usr/bin/1xClient
		procd_append_param command -u $username
		procd_append_param command -p $password
		procd_append_param command --device $ifname
		if [ $debug = 1 ]; then
			procd_append_param command --debug
		fi
		procd_set_param respawn
		procd_close_instance
	fi
}

service_triggers()
{
	procd_add_reload_trigger 1xClient
}

start_service()
{
	config_load 1xClient
	config_foreach Controller_1xClient 1xClient
}
